name: permacalendar
description: "Application professionnelle de gestion de jardinage en permaculture"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audioplayers: ^6.5.1
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^3.0.3
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.0
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^16.2.4
  
  # Network
  dio: ^5.4.0
  connectivity_plus: ^7.0.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.2.1
  path_provider: ^2.1.1
  shared_preferences: ^2.0.15
  device_info_plus: 12.2.0
  
  # Weather & Location
  geolocator: ^14.0.2
  weather: ^3.1.1
  
  # Export & Analytics
  csv: ^6.0.0
  pdf: ^3.10.7
  share_plus: ^12.0.0
  
  # Environment
  flutter_dotenv: ^6.0.0
  
  # Notifications
  flutter_local_notifications: ^19.4.2
  flutter_local_notifications_platform_interface: ^9.1.0
  flutter_local_notifications_linux: ^6.0.0
  
  # Charts & Visualization
  fl_chart: ^1.1.1
  
  


  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.7.1
  freezed: ^2.5.2
  riverpod_generator: ^3.0.0-dev.11
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  path: ^1.9.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
    - assets/images/
    - assets/images/plants/
    - assets/images/icons/
    - assets/images/backgrounds/
    - assets/images/social/
    - assets/images/legumes/
    - .env
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700



